### ISSUE TITLE
New Error List

### ISSUE THREAD

**Issue by smkplus** [Armour/Multiplayer-FPS#14]
![capture](https://user-images.githubusercontent.com/16706911/50901633-ac36b280-13cd-11e9-91a4-be39020f2630.PNG)

New bugs

Assets\Standard Assets\Cameras\Scripts\FreeLookCam.cs(3,27): error CS0234: The type or namespace name 'CrossPlatformInput' does not exist in the namespace 'UnityStandardAssets' (are you missing an assembly reference?)
Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\FirstPersonController.cs(3,27): error CS0234: The type or namespace name 'CrossPlatformInput' does not exist in the namespace 'UnityStandardAssets' (are you missing an assembly reference?)

Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\FirstPersonController.cs(4,27): error CS0234: The type or namespace name 'Utility' does not exist in the namespace 'UnityStandardAssets' (are you missing an assembly reference?)

Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\HeadBob.cs(3,27): error CS0234: The type or namespace name 'Utility' does not exist in the namespace 'UnityStandardAssets' (are you missing an assembly reference?)

Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\MouseLook.cs(3,27): error CS0234: The type or namespace name 'CrossPlatformInput' does not exist in the namespace 'UnityStandardAssets' (are you missing an assembly reference?)

Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\RigidbodyFirstPersonController.cs(3,27): error CS0234: The type or namespace name 'CrossPlatformInput' does not exist in the namespace 'UnityStandardAssets' (are you missing an assembly reference?)

Assets\Standard Assets\Characters\RollerBall\Scripts\BallUserControl.cs(3,27): error CS0234: The type or namespace name 'CrossPlatformInput' does not exist in the namespace 'UnityStandardAssets' (are you missing an assembly reference?)

Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\HeadBob.cs(10,16): error CS0246: The type or namespace name 'CurveControlledBob' could not be found (are you missing a using directive or an assembly reference?)

Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\HeadBob.cs(11,16): error CS0246: The type or namespace name 'LerpControlledBob' could not be found (are you missing a using directive or an assembly reference?)

Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\FirstPersonController.cs(22,34): error CS0246: The type or namespace name 'FOVKick' could not be found (are you missing a using directive or an assembly reference?)

Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\FirstPersonController.cs(24,34): error CS0246: The type or namespace name 'CurveControlledBob' could not be found (are you missing a using directive or an assembly reference?)

Assets\Standard Assets\Characters\FirstPersonCharacter\Scripts\FirstPersonController.cs(25,34): error CS0246: The type or namespace name 'LerpControlledBob' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Armour** [comment]
Hi, make sure you use the up-to-date code and also upgrade your unity version to 2018.3.0f2 or newer, I can't reproduce this on my side, also when you first load the game, there will be a bunch of warning and errors, but most of them are due to Standard Assets scripts, these scripts will be updated in the near future by Unity (hopefully) and warnings/errors should be gone at that time.

For now, you can safely ignore the errors and warnings as long as you can run the game. Let me know if you can't run the game.
