### ISSUE TITLE
Setup Photon Servers

### ISSUE THREAD

**Issue by vvlabs** [Armour/Multiplayer-FPS#17]
Great work on this! 

I would like to use this and edit it to my liking and deploy it. Which server file would I edit to setup Photon and how would I setup photon? 

If this is solved, I WILL donate via PAYPAL. 

PLEASE HELP!

**Comment by Armour** [comment]
Hi, add your [Photon ID](https://doc.photonengine.com/en-us/realtime/current/getting-started/obtain-your-app-id) to PhotonServerSettings under [this path](https://github.com/Armour/Multiplayer-FPS/tree/master/Assets/Photon/PhotonUnityNetworking/Resources) and it should work.

**Comment by vvlabs** [comment]
Can you elaborate? I know I need to copy the photon Id somewhere but the .asset file in your specified path does not contain readable text, just numbers.

**Comment by Armour** [comment]
Please open it in Unity, thanks.

<img width="558" alt="Screen Shot 2019-03-13 at 17 55 24" src="https://user-images.githubusercontent.com/5276065/54324091-65c22780-45b9-11e9-9beb-001b412b05d7.png">
<img width="363" alt="Screen Shot 2019-03-13 at 17 56 16" src="https://user-images.githubusercontent.com/5276065/54324113-7c687e80-45b9-11e9-9166-f4ea88c56735.png">

**Comment by vvlabs** [comment]
The servers do not seem to be working. I set up my servers and have deployed the fps at this test link:
https://ripx-llj.000webhostapp.com/
My app ID is in the settings but is not working.

**Comment by Armour** [comment]
Can I close this now?

**Comment by Armour** [comment]
Closed due to inactivity.
