### ISSUE TITLE
How do I play it with my friends. How do they join the game 

### ISSUE THREAD

**Issue by vishnudut** [Armour/Multiplayer-FPS#20]
How do I play this game with friends. How to add them to the game ?

**Comment by Armour** [comment]
1. Download Unity
2. Setup Phonton Server 
2. Use Uniy to build game into executable file
3. Copy and sent to your friends
4. Join with the same room name

**Comment by vishnudut** [comment]
Any Video or tutorial link to do it ? Because I have no experience in using photon server

**Comment by Armour** [comment]
I'll write one later this year，you can also check out their official documentations，basically you just need to register an account and then copy your app ID to the photon config file

**Comment by Armour** [comment]
#17

**Comment by Armour** [comment]
Closed due to inactivity.
