### ISSUE TITLE
Any of chance of this being updated to Photon 3?

### ISSUE THREAD

**Issue by input-variable** [Armour/Multiplayer-FPS#23]
If not, how easy do you think it would be for me to do it?

**Comment by Armour** [comment]
I can do it next week

**Comment by JohnTube** [comment]
@input-variable 

I want to clarify something about naming and versioning in Photon engine's world:

If you are referring to PUN or Photon Unity Networking, its current major version is 2.

Other Photon client SDKs and Photon Server SDK have their own versions. But the current major shared version is 4. 
Photon 3 is so old and outdated.

**Comment by input-variable** [comment]
> @input-variable
> 
> I want to clarify something about naming and versioning in Photon engine's world:
> 
> If you are referring to PUN or Photon Unity Networking, its current major version is 2.
> 
> Other Photon client SDKs and Photon Server SDK have their own versions. But the current major shared version is 4.
> Photon 3 is so old and outdated.

Ah! Thanks for clarifying.
